### ISSUE TITLE
Error at utils.js when querying

### ISSUE THREAD

**Issue by AkashAryal** [PragunSaini/vndb-api#3]
Hi!
When I try the following query: 
`get vn details,tags,screens,basic ( tags = [155,96,136] )`

I get an error:

> var status = response.match(/(\S+) {/)[1];
TypeError: Cannot read property '1' of null

**Comment by PragunSaini** [comment]
Thanks for opening this issue.

I have updated the package, fixing this bug, to **v1.0.3**.
